name: Repository maintenance

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  maintenance:
    uses: ObsidianPublisher/actions/.github/workflows/maintenance.yml@main
    with:
      CLEAN: true
      DRY_RUN: false
    secrets:
      GH_PAT: ${{ secrets.GITHUB_TOKEN }}
