name: Get latest release from template

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  pull-requests: write

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
jobs:
  update:
    uses: ObsidianPublisher/actions/.github/workflows/update.yml@main
    with:
      AUTO_MERGE: false
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
